app-name: "GIN-FLEX-ADMIN"
app-env: "dev"

jwt:
  secret: czs8lZsupQPuLEz2rNRdUBMSZS1gGpr2046VGkMsR
  expire: 86400
  refresh-expire: 604800
  issuer: gin-flex-admin

admin:
  username: admin
  password: $2a$10$B.V9TGN9A.czs8lZsupQPuLEz2rNRdUBMSZS1gGpr2046VGkMsR.q